version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: smartdrawer-backend:latest
    container_name: smartdrawer-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    #environment:
    #  NODE_ENV: production
    #volumes:
    #  - .:/app
    networks:
      - smartdrawer-net
networks:
  smartdrawer-net:
    driver: bridge
